name: Factions
author: Froward
main: Factions.Main
version: 1.0
commands:
  f:
    usage: "Erreur de la commande !
      	\n/f create <nomFaction>
		\n/f status
		\n/f f status <faction>
		\n/f list
		\n/f join <faction>
		\n/f accept
		\n/f leave
		\n/f disband <faction>"