name: Factions
author: Froward
main: Factions.Main
mcversion: 1.14.4
description: Le célebre plugin Factions revisité par Froward.
database: true
version: 1.0
commands:
  f:
    usage: "Erreur de syntaxe ! Essayez:
      	\n/f create <nomFaction>
		\n/f status
		\n/f f status <faction>
		\n/f list
		\n/f join <faction>
		\n/f accept
		\n/f leave
		\n/f disband <faction>
		\n/f leader <joueur>"